name: dartbook_theme
description: A web development tool for dartbook theme.
version: 1.0.0
homepage: https://github.com/lindeer/dartbook-theme

environment:
  sdk: '>=2.12.0 <4.0.0'

dev_dependencies:
  build_runner: ^2.4.0
  build_web_compilers: ^4.0.0
  lints: ^3.0.0
